website/mosaic/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^', include('mosaicportfolio.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

website/mosaicportfolio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth import views as auth_views

from tastypie.api import Api
import registration.views

import forms
import api

v1_api = Api(api_name='v1')
v1_api.register(api.UserProfileResource())
v1_api.register(api.UserResource())
v1_api.register(api.UserGraphResource())
v1_api.register(api.ProjectGraphResource())
v1_api.register(api.ProjectResource())
v1_api.register(api.RepositoryResource())

urlpatterns = patterns('mosaicportfolio.views',
    url(r'^api/rest/', include(v1_api.urls)),

    url(r'^api/worklist/(?P<abstract_type>\w+)/(?P<concrete_type>\w+)/deliver/', 'api_worklist_deliver', name='api_worklist_deliver'),
    url(r'^api/worklist/(?P<abstract_type>\w+)/(?P<concrete_type>\w+)/', 'api_worklist', name='api_worklist'),

    url(r'^register/$', registration.views.register,
            {'backend': 'registration.backends.simple.SimpleBackend',
             'form_class': forms.RegistrationForm}, name='registration_register'),

    url(r'^login/$', auth_views.login,
            {'template_name': 'registration/login.html',
             'authentication_form': forms.AuthenticationForm}, name='auth_login'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'registration/logout.html'}, name='auth_logout'),
    url(r'^password/change/$', auth_views.password_change, name='auth_password_change'),
    url(r'^password/change/done/$', auth_views.password_change_done, name='auth_password_change_done'),
    url(r'^password/reset/$', auth_views.password_reset, name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete, name='auth_password_reset_complete'),
    url(r'^password/reset/done/$', auth_views.password_reset_done, name='auth_password_reset_done'),

    url(r'^', include('social_auth.urls')),

    url(r'^portfolio/(?P<username>\w+)/', 'portfolio', name='portfolio'),
    url(r'^portfolio/', 'portfolio_redirect', name='portfolio'),

    url(r'^$', 'home', name='home')
)

website/mosaicportfolio/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class SiteKind:
    github = "github"
    values = [("github", "github")]

class RepositoryKind:
    git = "git"
    hg = "hg"
    values = [("git", "git"), ("hg", "hg")]

class WikiKind:
    github = "github"
    values = [("github", "github")]

class IssueTrackerKind:
    github = "github"
    values = [("github", "github")]

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')

    tag_line = models.CharField(max_length=256, blank=True)
    about = models.TextField(blank=True)

class UserLink(models.Model):
    user = models.ForeignKey(User, related_name='links')

    name = models.CharField(max_length=256)
    url = models.URLField(verify_exists=False)

def create_user_profile(**kwargs):
    if kwargs['created']:
        UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_user_profile, sender=User)

class UserSite(models.Model):
    user = models.ForeignKey(User)
    login = models.CharField(max_length=200)
    concrete_type = models.CharField(max_length=16, choices=SiteKind.values)

    def __str__(self):
        return "%s: %s@%s" % (self.user, self.login, self.concrete_type)

class Project(models.Model):
    user = models.ForeignKey(User, related_name='projects')
    name = models.CharField(max_length=200)
    tag_line = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return "%s@%s" % (self.user, self.name)

class Repository(models.Model):
    projects = models.ManyToManyField(Project, through='ProjectRepository', related_name='repositories')

    url = models.CharField(max_length=200)
    concrete_type = models.CharField(max_length=16, choices=RepositoryKind.values)
    last_updated = models.DateTimeField()

    class Meta:
        verbose_name_plural = "repositories"
        unique_together = [('concrete_type', 'url')]

    def save(self, *args, **kwargs):
        """
        Enforce a default last_updated timestamp sometime in the faraway past,
        makes it much more simple for us to get a prioritized list of repositories
        for processing on the back-ends.
        """

        if self.last_updated is None:
            self.last_updated = datetime.fromtimestamp(0)

        return super(Repository, self).save(*args, **kwargs)

    def __str__(self):
        return "%s(%s)" % (self.url, self.concrete_type)


class ProjectRepository(models.Model):
    project = models.ForeignKey(Project)
    repository = models.ForeignKey(Repository)

    login = models.CharField(max_length=200)
    
    def login_exits(self):
        return False
    
    def activity_count(self):
        return RepositoryActivity.objects.filter(repository=self.repository).count()
        
    def login_activity_count(self):
        return RepositoryActivity.objects.filter(repository=self.repository).filter(login=self.login).count()
        
    class Meta:
        verbose_name_plural = "project repositories"

    def __str__(self):
        return "%s@%s" % (self.login, self.repository)

class Wiki(models.Model):
    projects = models.ManyToManyField(Project, through='ProjectWiki')

    url = models.CharField(max_length=200)
    concrete_type = models.CharField(max_length=16, choices=WikiKind.values)

    def __str__(self):
        return "%s(%s)" % (self.url, self.concrete_type)

class ProjectWiki(models.Model):
    project = models.ForeignKey(Project)
    wiki = models.ForeignKey(Wiki)

    login = models.CharField(max_length=200)

    def __str__(self):
        return "%s@%s" % (self.login, self.wiki)

class IssueTracker(models.Model):
    projects = models.ManyToManyField(Project, through='ProjectIssueTracker')

    url = models.CharField(max_length=200)
    concrete_type = models.CharField(max_length=16, choices=IssueTrackerKind.values)

    def __str__(self):
        return "%s(%s)" % (self.url, self.concrete_type)

class ProjectIssueTracker(models.Model):
    project = models.ForeignKey(Project)
    issue_tracker = models.ForeignKey(IssueTracker)

    login = models.CharField(max_length=200)

    def __str__(self):
        return "%s@%s" % (self.login, self.issue_tracker)
     
class Activity(models.Model):
    date = models.DateTimeField()
    login = models.CharField(max_length=200)

    class Meta:
        abstract = True
         
class RepositoryActivity(Activity):
    repository = models.ForeignKey(Repository, related_name='activities')

    class Meta:
        verbose_name_plural = "repository activities"
        get_latest_by = 'date'

    def __str__(self):
        return "%s@%s(%s)" % (self.login, self.repository, self.date)

class IssueTrackerActivity(Activity):
    issue_tracker = models.ForeignKey(IssueTracker)

    class Meta:
        verbose_name_plural = "issue tracker activities"

    def __str__(self):
        return "%s@%s(%s)" % (self.login, self.issue_tracker, self.date)

class WikiActivity(Activity):
    wiki = models.ForeignKey(Wiki)

    class Meta:
        verbose_name_plural = "wiki activities"

    def __str__(self):
        return "%s@%s(%s)" % (self.login, self.wiki, self.date)

website/mosaicportfolio/forms.py
from django.contrib.auth.forms import AuthenticationForm as BaseAuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django import forms

from registration.backends.simple import RegistrationForm as BaseRegistrationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class AuthenticationForm(BaseAuthenticationForm):

    helper = FormHelper()
    helper.add_input(Submit('login', _(u'Log in')))

class RegistrationForm(BaseRegistrationForm):

    helper = FormHelper()
    helper.add_input(Submit('register', _(u'Register')))

website/mosaicportfolio/views.py
from datetime import timedelta, datetime
import time
import simplejson

from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed, HttpResponse, Http404, HttpResponseBadRequest, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import  User

from .models import Repository, RepositoryActivity
import logging

logger = logging.getLogger(__name__)

def home(request):
    return render(request, "mosaicportfolio/home.html")

@login_required
def portfolio_redirect(request):
    return redirect(reverse('portfolio', kwargs={'username': request.user.username}))

def portfolio(request, username):
    user = get_object_or_404(User.objects.select_related(), username=username)

    isowner = request.user.is_authenticated() and request.user.username == user.username

    return render(request, "mosaicportfolio/portfolio.html", {
        'portfolio': user,
        'isowner': isowner
    })

def api_worklist(request, abstract_type, concrete_type):
    """
    Returns a list of work items (as of now this list has only one item in it at a time)

    Each item is a dictionary {"url": <string>, "since": <string, unix timestamp>}

    Since indicates the latest item we have recorded for that particular repository, e.g. the
    worker should only look for items which are newer than this time.
    """

    if not request.GET.has_key('token') or request.GET.get('token') != settings.MOSAIC_WORKER_PRIVATE_TOKEN:
        return HttpResponseForbidden()

    threshold = timezone.now() - timedelta(days=1)

    items = []

    if abstract_type == 'repository':
        repositories = Repository.objects.all()\
                       .filter(concrete_type=concrete_type)\
                       .exclude(last_updated__gt=threshold)\
                       .order_by('last_updated')[:1]

        for repository in repositories:

            try:
                since = time.mktime(repository.activities.latest().date.timetuple())
            except RepositoryActivity.DoesNotExist:
                since = None

            items.append({'url': repository.url,
                          'since': since})

    else:
        return Http404()

    return HttpResponse(simplejson.dumps(items), content_type='application/json')

@csrf_exempt
def api_worklist_deliver(request, abstract_type, concrete_type):
    """
    Accepts a delivery of activities for a single repository.

    A post request is accepted with the POST parameter "payload", which must be a
    JSON formatted dictionary with the following contents:

    {
        "url": <string, repository url>,
        "activities": [
            {
                "date": <string, unix timestamp>,
                "login": <string, user identifier>
            } ...
        ]
    }

    """
    
    if request.method != 'POST':
        return HttpResponseNotAllowed(permitted_methods=['POST'])
    
    if not request.GET.has_key('token') or request.GET.get('token') != settings.MOSAIC_WORKER_PRIVATE_TOKEN:
        return HttpResponseForbidden()
    
    if abstract_type == 'repository':

        try:
            payload = simplejson.loads(request.POST['payload'])

            repository = get_object_or_404(Repository, url=payload['url'], concrete_type=concrete_type)

            repository.last_updated = timezone.now()
            repository.save()

            for activity in payload['activities']:
                RepositoryActivity.objects.create(
                    repository=repository,
                    date=datetime.fromtimestamp(float(activity['date']), tz=timezone.get_current_timezone()),
                    login=activity['login']
                )
            return HttpResponse()

        except simplejson.JSONDecodeError as e:
            logger.exception(e)
            return HttpResponseBadRequest()

    else:
        return Http404()

website/mosaicportfolio/templates/mosaicportfolio/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MOSAiC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/mosaic.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block extraheaders %}{% endblock %}

</head>
<body>

<div class="container">

<header class="row page-header">

    <div class="right text-right">
        {% if user.is_authenticated %}
        <p>Welcome, <a href="{% url portfolio user.username %}">{{ user.username }}</a>. <a href="{% url auth_logout %}">Logout</a></p>
        {% else %}
        <a href="{% url registration_register %}">Register</a> or  <a href="{% url auth_login %}">Log In</a> <br/>
        Log in with {% for name in social_auth.backends %}
            <a rel="nofollow" href="{% url socialauth_begin backend=name %}">{{ name|title }}</a>
        {% endfor %}
        {% endif %}
    </div>

    <a class="logo" href="{% url home %}"><h1>MOSAiC <small>My Open Source Activity Collection</small></h1></a>

</header>

{% block content %}{% endblock %}

    <footer class="row">
        <div class="span12">
            <p class="right">Powered by <a href="http://www.djangoproject.org">Django</a></p>
            <p>Created by <a href="{% url portfolio "esbena" %}">Esben Andreasen</a> and <a href="{% url portfolio "sema" %}">Casper Svenning Jensen</a></br>
            <a href="mailto:casper@svenningjensen.dk">Contact us</a>, <a href="https://github.com/sema/django-2012/issues">Issue tracker</a></p>

        </div>
    </footer>

</div>

{% if GOOGLE_ANALYTICS %}
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '{{ GOOGLE_ANALYTICS }}']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>
{% endif %}

</body>
</html>

website/mosaicportfolio/templates/mosaicportfolio/home.html
{% extends 'mosaicportfolio/base.html' %}

{% block content %}

<section class="row">

    <div class="hero-unit">
            <h1>Need a Code Portfolio?</h1>
            <section class="row">
            <span class='span7'>
	            <h2>Stitch together a MOSAiC of your contributions to Open Source projects</h2>
	
	            <p>Use it to show your work to fellow programmers and potential employers. We help you build the portfolio and provide live statistics on your contributions to Open Source projects of your choice.</p>
	            <p>Why? <a href="http://www.codinghorror.com/blog/2004/10/a-programmers-portfolio.html">Every programmer should have a Portfolio</a> that's why.</p>
	            <br/>
	            <p><a href="{% url registration_register %}" class="btn btn-primary btn-large">Let us host your portfolio</a>  <a href="http://github.com/sema/django-2012" class="btn btn-primary btn-large">Host it yourself</a></p>
	        </span>
	        <span class='span4'><a href='{{ STATIC_URL }}img/screenshot.png' class='thumbnail'><img src="{{ STATIC_URL }}img/screenshot.png" alt='example-screenshot'/></a></span>
            </section>
    </div>

</section>

<section class="row">

    <div class="span4">
        <h3>Your Code Portfolio</h3>

        <dl class="dl-horizontal">
            <dt>You</dt>
            <dd>The communities you participate in, and the technologies you work with.</dd>

            <dt>Projects</dt>
            <dd>The projects you have contributed to and examples of your work</dd>

            <dt>Involvement</dt>
            <dd>Commits, patches, issues, wiki edits...</dd>
        </dl>
    </div>

    <div class="span4">
        <h3>Keeping it Fresh</h3>

        <p>Link projects to <strong>repositories</strong>, <strong>issue trackers</strong>, and <strong>code-hosting sites</strong> and keep your Code Portfolio fresh.</p>

        <p>We'll show your <strong>Open Source activity</strong> and let you keep it fresh with as little effort as possible.</p>
    </div>

    <div class="span"  id='we_support' >
        <h3>We Support</h3>

        <dl class="dl-horizontal">
            <dt>Code Hosting:</dt>
            <dd>
            None yet
            </dd>
			<br/>
            
            <dt>Repositories:</dt>
            <dd>
                        	<a href='http://git-scm.com/'><img class='branding-icon' src="{{ STATIC_URL }}img/git.png" alt='git'/></a> <a href='http://mercurial.selenic.com/'><img class='branding-icon' src="{{ STATIC_URL }}img/mercurial.png" alt='mercurial'/></a></dd>
            </dd>
			<br/>
            <dt>Issue trackers:</dt>
            <dd>None yet</dd>

        </dl>
    </div>

</section>

{% endblock %}

website/mosaicportfolio/templates/mosaicportfolio/portfolio.html
{% extends 'mosaicportfolio/base.html' %}
{% load htmlsanitizer %}

{% block extraheaders %}
<link href="{{ STATIC_URL }}css/midgardnotif.css" rel="stylesheet">

<script type="text/javascript" src="{{ STATIC_URL }}js/libs/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/libs/underscore.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/libs/backbone.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/libs/backbone.tastypie.js"></script>

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/libs/hallo.js"></script>

<script type="text/javascript" src="{{ STATIC_URL }}js/app/graphing.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/app/models.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/app/views.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/app/init.js"></script>
{% endblock %}

{% block content %}

    {% if isowner %}
    <section class="row portfolio-toolbar">
        <div class="span6 create-toolbar-left">&nbsp;</div>
        <div class="span6 create-toolbar-right">
            <a class="btn btn-primary pull-right doEdit"><i class="icon-edit icon-white"></i> Edit</a>
            <a class="btn btn-primary pull-right doSave"><i class="icon-edit icon-white"></i> Save</a>
        </div>
    </section>
    {% endif %}

    <section class="row portfolio-profile">

        <div class="span12">
            <input type="hidden" id="user_pk" value="{{ portfolio.pk }}"/>
        	<h1 class="editable portfolio-name">{% if portfolio.first_name %}{{ portfolio.first_name|sanitize_html }}{% else %}{{ portfolio.username }}{% endif %}</h1>
        	<h3 class="editable portfolio-tagline">{{ portfolio.get_profile.tag_line|sanitize_html }}</h3>
        </div>

        <div class="span12">
        <div class="row">
            <div class="span6">
                <p class="editable portfolio-about">{{ portfolio.get_profile.about|sanitize_html }}</p>

                <div>
                    <!--<a href="mailto:{{ portfolio.email }}" class="btn btn-primary btn-large"><i class="icon-envelope icon-white"></i> E-mail me</a>-->

                    {% for link in portfolio.links.all %}
                        <a href="#" class="btn btn-primary btn-large"><i class="icon-globe icon-white"></i> Linked in</a>
                    {% endfor %}
                </div>

            </div>
	        <span class="span5">
	            <h4>Overview</h4>
	            <div class="thumbnail" id="usergraph"></div>
    	    </span>
        </div>
        </div>
    </section>
	<div>
		<br/>
	</div>
    <section class="row">
	
        <div class="span12 projects">
            <div>
                <a class="btn btn-primary pull-right newProject"><i class="icon-plus icon-white"></i> New Project</a>
                <h4>Open Source Projects <span class="badge project-count"></span></h4>
            </div>

			<div class='alert alert-info alert-block' style="margin-top: 1em;">
                <p>Please be patient while we load and refresh data about your activities, we rely on external data sources and can not guarantee how fast they respond to changes.</p>
            </div>

            <div class="project-list">
            {% for project in portfolio.projects.all %}
            <div class="project">
                <input type="hidden" class="project-id" value="{{ project.pk }}" />
                <div class="row">
                    <div class="span12">
                        <h2 style="display: inline;" class="editable project-name">{{ project.name|sanitize_html }}</h2> <h2 style="display: inline;"><small class="editable project-tagline">{{ project.tag_line|sanitize_html }}</small></h2>
                        <!--<span class="label">Python</span> <span class="label label-info">Django</span> <span class="label label-success">Web</span>-->
                    </div>
                </div>

                <div class="row">
                    <div class="span9">
                        <div class="editable project-description">
                            <p>{{ project.description|sanitize_html }}</p>
                        </div>
                        <div class='username-warning alert alert-info alert-block' style="margin-top: 1em;">
            			    <p>Your username will be matched with the author of each commit in the repositories, your username might be your full name, your email, your user name or something else. Please review the log messages of your repositories, and add an entry per relevant username.</p>
			            </div>


                        {% for repository in project.projectrepository_set.all %}
                            <div class="repository">
                            <form class="form-inline" class="row">
                                <input type="hidden" class="repository-id" value="{{ repository.pk }}" />
								
                                <select class="repository-type span1">
                                    <option {% ifequal repository.repository.concrete_type 'git' %}selected{% endifequal %} value="git">git</option>
                                    <option {% ifequal repository.repository.concrete_type 'hg' %}selected{% endifequal %} value="hg">hg</option>
                                </select>
                                <input class="repository-url span3 input-small" type="text" value="{{ repository.repository.url }}" />
                                <input class="repository-login span3 input-small" type="text" value="{{ repository.login }}" />
								<span class='span2 right repository-activity-count'><span class='repository-activity-count-badge badge'><span class='login'>{{ repository.login_activity_count }}</span> / <span class='total'>{{ repository.activity_count }}</span> commits</span></span>
                            </form>
                            </div>
                        {% endfor %}

                        <div class="repository-sample">
                        <form class="form-inline" class="row">

                            <select class="repository-type span1">
                                <option value="git">git</option>
                                <option value="hg">hg</option>
                            </select>
                            <input type="text" class="repository-url span3 input-small" placeholder="Repository URL" />
                            <input type="text" class=" repository-login span3 input-small" placeholder="Commit username" />
                        </form>
                        </div>
                    </div>

                    <div class="span3">
                        <div class="graph" id="projectgraph{{ project.pk }}">
                        </div>
                    </div>

                </div>
            </div>

            {% empty %}

            <div class="no-project-message">
                <h2>No projects</h2>

                {% if isowner %}
                    <p class="alert alert-info">Improve your portfolio by adding projects you have worked on.</p>
                {% endif %}
            </div>

            {% endfor %}
            </div>

            <div class="project-sample">
            <input type="hidden" class="project-id" value="" />

                <div class="row">
                    <div class="span8">
                        <h2 style="display: inline;" class="editable project-name">Project name</h2> <h2 style="display: inline;"><small class="editable project-tagline">and short tagline</small></h2>
                    </div>
                </div>

                <div class="row">
                    <div class="span5">
                        <div class="editable project-description">
                        <p>Insert long description here</p>
                        </div>

                        <div class="repository-sample">
                            <form class="form-inline" class="row">

                                <select class="repository-type span1">
                                    <option value="git">git</option>
                                    <option value="hg">hg</option>
                                </select>
                                <input type="text" class="repository-url span2 input-small" placeholder="Repository URL" />
                                <input type="text" class=" repository-login span2 input-small" placeholder="Commit username" />
                            </form>
                        </div>

                    </div>

                    <div class="span3">

                    </div>
                </div>


            </div>

        </div>
    </section>

{% endblock %}